networks:
  home-network:
    name: home-network

services:

  mpc:
    build:
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    container_name: jira_mcp
    hostname: jira_mcp
    restart: always
    networks:
      - home-network

